apiVersion: v1
kind: Service
metadata:
  name: {{ include "projectname-gateway.fullname" . }}-management
  labels:
  {{- include "projectname-gateway.labels" . | nindent 4 }}
  annotations:
    management.port: "8081"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "projectname-gateway.selectorLabels" . | nindent 4 }}
