{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "review-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "review-service.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "review-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- end -}}
