spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - https://projectname-tst.example.com
              - https://projectname-tst.azure.example.com
              - http://localhost:4200
      routes:
        - id: mc-change-notice-import-scope-items
          uri: http://LB-host.example.COM:23507/change-notices
          predicates:
            - Path=/api/mc/v0.1/change-notices/{segment}/change-objects/**
            - Method=POST
          filters:
            - StripPrefix=3
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: aurora-comments
          uri: http://LB-host.example.COM:23524/comments
          predicates:
            - Path=/api/aurora/comments
            - Method=POST
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: mc
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/mc/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: gds-legacy
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/gds/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: config
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/config/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: id-generator
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/id-generator/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: air
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/air/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: cerberus
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/cerberus/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: sdl
          uri: http://LB-host.example.COM:23816
          predicates:
            - Path=/api/sdl/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: teamcenter
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/teamcenter/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: sap-mdg
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/sap-mdg/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: exchange
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/exchange/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: hana-legacy
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/hana/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: hana-cache
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/hana-cache/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: actuator-health
          uri: http://localhost:8081
          predicates:
            - Path=/actuator/health
            - Method=GET
        - id: projectname-notification-service
          uri: http://projectname-notification-service:8080
          predicates:
            - Path=/api/notification-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: review-service
          uri: http://review-service:8080
          predicates:
            - Path=/api/review-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: change-request-service
          uri: http://change-request-service:8080
          predicates:
            - Path=/api/change-request-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: release-package-service
          uri: http://release-package-service:8080
          predicates:
            - Path=/api/release-package-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: impacted-item-service
          uri: http://impacted-item-service:8080
          predicates:
            - Path=/api/impacted-item-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: projectname-configuration-service
          uri: http://projectname-configuration-service:8080
          predicates:
            - Path=/api/configuration-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: myimpact-scm-scia-service
          uri: http://otherproject-gateway.otherproject:80/api/scia-service
          predicates:
            - Path=/api/scia-service/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay            
        - id: user-photo
          uri: http://projectname-frontend:8080
          predicates:
            - Path=/_layouts/15/userphoto.aspx
          filters:
            - RemoveRequestParameter=size
            - RemoveRequestParameter=accountname
            - RewritePath=/_layouts/15/userphoto.aspx,/assets/icons/blank-portrait.png
        - id: gds-service
          uri: http://gds-service:8080
          predicates:
            - Path=/api/gds-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: hana-service
          uri: http://hana-service:8080
          predicates:
            - Path=/api/hana-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: projectname-ui
          uri: http://projectname-frontend:8080
          predicates:
            - Path=/**
